name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  blogs:
    name: "Blogs"
    runs-on: node16
    steps:
       - name: "📥  Fetching Repository Contents"
         uses: actions/checkout@main

       - name: "📚  Hashnode Updater"
         uses: "varunsridharan/action-hashnode-blog@main"
         with:
          USERNAME: 'Devhopefuture' # Hashnode Username
          BLOG_URL: 'https://devhopefuture.hashnode.dev' # Blog URL
          COUNT: 5 # MAX Visisble
          STYLE: "list"

